---

# Get devops config and status, include core, ci, cd
- include: get_devops_config.yaml
  tags: flag

- name: install core
  import_tasks: core.yaml
  when: devops_enabled.stdout == "true" and status_core.stdout != "enabled"

- name: install cd
  import_tasks: cd.yaml
  when: devops_enabled.stdout == "true" and devops_cd_enabled.stdout == "true" and status_cd.stdout != "enabled"

- name: install ci
  import_tasks: ci.yaml
  when: devops_enabled.stdout == "true" and devops_ci_enabled.stdout == "true" and status_ci.stdout != "enabled"