---
devops:
  jenkinsVolumeSize: "16Gi"
  jenkinsMemoryLim: "{{ jenkins_memory_lim |default('4Gi') }}"
  jenkinsMemoryReq: "{{ jenkins_memory_req |default('4Gi') }}"
  jenkinsCpuReq: "{{ jenkins_cpu_req |default('0.5') }}"
  jenkinsCpuLim: "{{ jenkins_cpu_lim |default('1') }}"


EMAIL_SMTP_HOST: mail.example.com
EMAIL_FROM_ADDR: admin@example.com
EMAIL_FROM_NAME: KubeSphere
EMAIL_USE_SSL: false
EMAIL_SMTP_PORT: 465
EMAIL_FROM_PASS: P@ssw0rd

sonar_account_user: ks-devops

harbor_domain: harbor.devops.kubesphere.local


sonarqube_enable: true

sonarqube_user_name: sonarqube
sonarqube_user_passwd: sonarqube
