nameOverride: "istio-system"
fullnameOverride: "kiali-operator"

image:
  repo: kubesphere/kiali-operator
  tag: v1.50.1
  pullPolicy: IfNotPresent
  pullSecrets: []

# Defines where the operator will look for Kial CR resources. "" means "all namespaces".
watchNamespace: "istio-system"

allowAdHocKialiImage: true