- name: KubeSphere | Getting curator installation files
  copy:
    src: "elasticsearch-curator"
    dest: "{{ kubesphere_dir }}/"


- name: KubeSphere | Creating custom manifests
  template:
    src: "{{ item.file }}.j2"
    dest: "{{ kubesphere_dir }}/elasticsearch-curator/{{ item.file }}"
  with_items:
    - { name: custom-values-elasticsearch-curator, file: custom-values-elasticsearch-curator.yaml }


# Creating elasticsearch-credentials secret used to connect external es with basic auth enabled.
- name: KubeSphere | Creating elasticsearch credentials secret
  shell: >
    {{ bin_dir }}/kubectl create secret generic elasticsearch-credentials --from-literal="username={{ common.es.basicAuth.username }}" --from-literal="password={{ common.es.basicAuth.password }}" --type=kubernetes.io/basic-auth -n kubesphere-logging-system
  register: secret
  failed_when: "secret.stderr and 'already exists' not in secret.stderr"
  until: secret is succeeded
  retries: 5
  delay: 10
  when:
    - "common.es.basicAuth.enabled is defined"
    - "common.es.basicAuth.enabled == true"
    - "common.es.basicAuth.password is defined and common.es.basicAuth.password != ''"
    - "common.es.basicAuth.username is defined and common.es.basicAuth.username != ''"


- name: KubeSphere | Getting Elasticsearch host
  shell: >
    {{ bin_dir }}/kubectl get cm -n kubesphere-system kubesphere-config -o jsonpath='{.data.kubesphere\.yaml}' | grep "logging:" -A 2 | grep "host" | awk '{print $2}'
  register: es_host
  failed_when: false


- block:
  # Update clusterconfig (cc) status
  - name: KubeSphere | Importing es status
    shell: >
      {{ bin_dir }}/kubectl patch cc ks-installer
      --type merge
      -p '{"status": {"es": {"status": "enabled", "enabledTime": "{{ lookup('pipe','date  +%Y-%m-%dT%H:%M:%S%Z') }}"}}}'
      -n kubesphere-system
    register: cc_result
    failed_when: "cc_result.stderr and 'Warning' not in cc_result.stderr"
    until: cc_result is succeeded
    retries: 5
    delay: 3

  when:
    - common.es.externalElasticsearchHost is not defined or (common.es.externalElasticsearchHost is defined and common.es.externalElasticsearchHost == "")
    - common.es.externalElasticsearchPort is not defined or (common.es.externalElasticsearchPort is defined and common.es.externalElasticsearchPort == "")
    - es_host.stdout is defined
    - es_host.stdout == "" or es_host.stdout == "http://elasticsearch-logging-data.kubesphere-logging-system.svc:9200"

# Deploy elasticsearch curator
- block:
  # - name: KubeSphere | Checking elasticsearch-logging-curator
  #   shell: >
  #     {{ bin_dir }}/helm list elasticsearch-logging-curator
  #   register: curator_check
  #   ignore_errors: True


  - name: KubeSphere | Deploying elasticsearch-logging-curator
    shell: >
      {{ bin_dir }}/helm upgrade --install elasticsearch-logging-curator
      {{ kubesphere_dir }}/elasticsearch-curator/elasticsearch-curator-1.3.3.tgz
      -f {{ kubesphere_dir }}/elasticsearch-curator/custom-values-elasticsearch-curator.yaml
      --namespace kubesphere-logging-system
    when:
      - common.es.curator is defined and common.es.curator.enabled is defined and common.es.curator.enabled
    #   - (curator_check.stdout.find("DEPLOYED") == -1) or (curator_check.stdout.find("5.5.4-0217") == -1)