apiVersion: v1
items:
- apiVersion: alerting.kubesphere.io/v2beta1
  kind: GlobalRuleGroup
  metadata:
    annotations:
      alerting.kubesphere.io/initial-configuration: '{"apiVersion":"alerting.kubesphere.io/v2beta1","kind":"GlobalRuleGroup","metadata":{"annotations":{},"labels":{"alerting.kubesphere.io/builtin":"true","alerting.kubesphere.io/enable":"true"},"name":"ks-apiserver","namespace":"kubesphere-monitoring-system"},"spec":{"rules":[{"alert":"ksApiSlow","annotations":{"message":"99th percentile of requests is {{ $value }}s on ks-apiserver instance {{ $labels.instance }} for {{ $labels.verb }} {{ $labels.resource }}.{{ $labels.group }}/{{ $labels.version }}","runbook_url":"https://alert-runbooks.kubesphere.io/runbooks/kubesphere/ksapislow","summary":"ks-apiserver requests are slow."},"expr":"histogram_quantile(0.99, sum by(instance,group,resource,verb,version,le,cluster) (rate(ks_server_request_duration_seconds_bucket{group!=\"terminal.kubesphere.io\", job=\"ks-apiserver\"}[5m]))) > 5\n","for":"10m","labels":{"rule_id":"3f5d58fdbd68199d4ff515bfd09a2f87"},"severity":"critical"},{"alert":"ksApiserverDown","annotations":{"description":"ksApiserver has disappeared from Prometheus target discovery.","runbook_url":"https://alert-runbooks.kubesphere.io/runbooks/kubesphere/ksapiserverdown","summary":"Target disappeared from Prometheus target discovery."},"expr":"absent(up{job=\"ks-apiserver\"} == 1)\n","for":"15m","labels":{"rule_id":"766f549cf2737e1adc0c62e4f5fd0ba6"},"severity":"critical"}]}}'
    labels:
      alerting.kubesphere.io/builtin: "true"
      alerting.kubesphere.io/enable: "true"
    name: ks-apiserver
    namespace: kubesphere-monitoring-system
  spec:
    rules:
    - alert: ksApiSlow
      annotations:
        message: 99th percentile of requests is {{ $value }}s on ks-apiserver instance {{ $labels.instance }} for {{ $labels.verb }} {{ $labels.resource }}.{{ $labels.group }}/{{ $labels.version }}
        runbook_url: https://alert-runbooks.kubesphere.io/runbooks/kubesphere/ksapislow
        summary: ks-apiserver requests are slow.
      expr: |
        histogram_quantile(0.99, sum by(instance,group,resource,verb,version,le,cluster) (rate(ks_server_request_duration_seconds_bucket{group!="terminal.kubesphere.io", job="ks-apiserver"}[5m]))) > 5
      for: 10m
      labels:
        rule_id: 3f5d58fdbd68199d4ff515bfd09a2f87
      severity: critical
    - alert: ksApiserverDown
      annotations:
        description: ksApiserver has disappeared from Prometheus target discovery.
        runbook_url: https://alert-runbooks.kubesphere.io/runbooks/kubesphere/ksapiserverdown
        summary: Target disappeared from Prometheus target discovery.
      expr: |
        absent(up{job="ks-apiserver"} == 1)
      for: 15m
      labels:
        rule_id: 766f549cf2737e1adc0c62e4f5fd0ba6
      severity: critical
- apiVersion: alerting.kubesphere.io/v2beta1
  kind: GlobalRuleGroup
  metadata:
    annotations:
      alerting.kubesphere.io/initial-configuration: '{"apiVersion":"alerting.kubesphere.io/v2beta1","kind":"GlobalRuleGroup","metadata":{"annotations":{},"labels":{"alerting.kubesphere.io/builtin":"true","alerting.kubesphere.io/enable":"true"},"name":"ks-controller-manager","namespace":"kubesphere-monitoring-system"},"spec":{"rules":[{"alert":"ksControllerManagerDown","annotations":{"description":"ksControllerManager has disappeared from Prometheus target discovery.","runbook_url":"https://alert-runbooks.kubesphere.io/runbooks/kubesphere/kscontrollermanagerdown","summary":"Target disappeared from Prometheus target discovery."},"expr":"absent(up{job=\"ks-controller-manager\"} == 1)\n","for":"15m","labels":{"rule_id":"6367d0bcc67cf87eab8fb4e72e2285be"},"severity":"critical"}]}}'
    labels:
      alerting.kubesphere.io/builtin: "true"
      alerting.kubesphere.io/enable: "true"
    name: ks-controller-manager
    namespace: kubesphere-monitoring-system
  spec:
    rules:
    - alert: ksControllerManagerDown
      annotations:
        description: ksControllerManager has disappeared from Prometheus target discovery.
        runbook_url: https://alert-runbooks.kubesphere.io/runbooks/kubesphere/kscontrollermanagerdown
        summary: Target disappeared from Prometheus target discovery.
      expr: |
        absent(up{job="ks-controller-manager"} == 1)
      for: 15m
      labels:
        rule_id: 6367d0bcc67cf87eab8fb4e72e2285be
      severity: critical
kind: List
